### PR TITLE
Add initial version of images

### PR DESCRIPTION
**Pull request by tristan957**
Included are Fedora 36, Debian 11 for s390x, and Ubuntu
18.04/20.04/22.04.

Signed-off-by: Tristan Partin <tristan@partin.io>

### CODE REVIEW

**Comment by tristan957** [comment]
@bhaveshvasandani I think this is ready. Pay attention to the versioning scheme, the events that this is triggered, and the test script.

**Comment by tristan957** [comment]
And then please mark the shellcheck and image jobs as required.

**Review by bhaveshvasandani — APPROVED** [review]

**Comment by tristan957** [comment]
@smoyergh should I add an copyright headers to these files? Not sure what the policy is. Also I notice that there is not currently a license file in this repo? Should I add one.

**Comment by smoyergh** [comment]
Re copyrights, you mean in the workflows and containerfiles?  I don't see any value in doing so.  Re license file, I also suspect that's low value but go ahead and add it anyway just so there's no confusion.

**Comment by tristan957** [comment]
> Re copyrights, you mean in the workflows and containerfiles?

Yes.

> Re license file, I also suspect that's low value but go ahead and add it anyway just so there's no confusion.

Your wish is my command!

**Pull request merged**
